### ISSUE TITLE
Several glitches with role opencanary

### ISSUE THREAD

**Issue by martin-haller** [patron-it/ansible-opencanary#1]
Hi, I did a test installation and found several issues with role opencanary:

- [x] it is necessary to allow OpenCanary program to bind privilege ports (<1024). Could by done by `setcap CAP_NET_BIND_SERVICE=+eip /home/opencanary/.virtualenv/bin/python3`
- [x] It is necessasry to allow opencanary user to use sudo for iptables command (needed by port module). Could be done by `echo "opencanary ALL=(root) NOPASSWD: /sbin/iptables" > /etc/sudoers.d/020_opencanary-nopasswd`
- [x] It is necessary to allow opencanary.service to be automaticaly started with user opencanary. Could be done by `export XDG_RUNTIME_DIR="/run/user/$UID" && export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus" && systemctl --user enable opencanary` (run under user opencanary). The exports are necessary to be systemctl functional under SSH connection.

**Comment by webknjaz** [comment]
1.) I've solved this more granularly with authbind: e177ffb6b1fe12c9a3ff487eacf8c2117de0c631
3.) This has already been solved a month ago with `environment` setting: https://github.com/patron-it/ansible-opencanary/commit/0640d68aa64fc12317e742d00d67d0c68dddcbe2#diff-b53526f58340b9c206b05605d2b1fe6cR27.
Are you sure this is what's happening? Maybe you need to try it with a modern version of Ansible?

**Comment by webknjaz** [comment]
3.) and with `enabled` setting: https://github.com/patron-it/ansible-opencanary/commit/0640d68aa64fc12317e742d00d67d0c68dddcbe2#diff-e7bc9cfe2608f60cf8bc31263f2b1aceR32

**Comment by webknjaz** [comment]
2.) I'll do this but honestly invoking iptables from the app is a bad architectural decision. It should be done at the pre-configuration step so that the app wouldn't need any elevated privileges at all...

**Comment by webknjaz** [comment]
2.) Solved with aafc5290b4ba3599ae28acd341e3e618d05a83fe a bit more precisely allowing only `iptables -t mangle ...`, not whole `iptables ...` list of subcommands.
