### ISSUE TITLE
Bug: opencanary role: ensure that openacary service is started

### ISSUE THREAD

**Issue by martin-haller** [patron-it/ansible-opencanary#2]
![honeypot-bug](https://user-images.githubusercontent.com/34276685/50678511-547bfe00-0fff-11e9-858f-77be2789cb4e.png)

**Comment by webknjaz** [comment]
@Patrhal this issue probably happens because you use outdated Ansible version. Could you please try Ansible 2.7+ ?

P.S. Please copy-paste logs instead of using screenshots. They need zooming and it's impossible to copy-paste text from pictures.

**Comment by webknjaz** [comment]
For example, my version is
```console
➜ ansible --version                  
ansible 2.7.2
  config file = ~/src/github/patron-it/ansible-opencanary/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.pyenv/versions/3.7.1/envs/ansible-opencanary-py3.7.1-pyenv-venv/lib/python3.7/site-packages/ansible
  executable location = ~/.pyenv/versions/ansible-opencanary-py3.7.1-pyenv-venv/bin/ansible
  python version = 3.7.1 (default, Oct 21 2018, 21:08:23) [GCC 7.3.0]
```

**Comment by martin-haller** [comment]
Ok, I have updated my DEV VM from Debian stretch-backports (Ansible 2.6.3) to Debian SID (Ansible 2.7.5) and the error is gone.

**Comment by webknjaz** [comment]
JFYI you can also `pip install  --user -U ansible` to and have it in your userspace rather than on system level. That's how I use it so that it's independent of system-managed stuff.
